apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: researchnu-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - api.researchnu.com
      secretName: researchnu-tls
  rules:
    - host: api.researchnu.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: researchnu-api
                port:
                  number: 80